"""Adding created at for users

Revision ID: 62cf0a02a2c9
Revises: 04ef402c4795
Create Date: 2020-11-25 09:56:12.994616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cf0a02a2c9'
down_revision = '04ef402c4795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_on')
    # ### end Alembic commands ###
