"""create posts model and associated relationships

Revision ID: 50f97b31db47
Revises: 43e5a05f7f75
Create Date: 2020-11-20 23:09:04.593503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f97b31db47'
down_revision = '43e5a05f7f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddit', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('subreddit', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddit', 'updated_on')
    op.drop_column('subreddit', 'created_on')
    # ### end Alembic commands ###
